An unfancy Emacs extension for [[https://huggingface.co/bigcode/starcoder]] integration.

* Installation

Add one of those to your configuration.

#+begin_src elisp

;; package-vc.el (built-in from Emacs 29 and above)
(unless (package-installed-p 'starhugger)
  (package-vc-install '(starhugger :url "https://gitlab.com/daanturo/starhugger.el")))

;; straight.el
(straight-use-package '(starhugger :url "https://gitlab.com/daanturo/starhugger.el"))

;; Doom
(package! starhugger (:url "https://gitlab.com/daanturo/starhugger.el"))

;; elpaca.el
(elpaca (starhugger :url "https://gitlab.com/daanturo/starhugger.el"))

#+end_src

Or any package manager of your choice.

This package also requires those dependencies: [[https://github.com/emacs-compat/compat][compat]], [[https://github.com/magnars/dash.el][dash]], [[https://github.com/Malabarba/spinner.el][spinner]].

* Usage

** Primary commands

- Direct completion: call ~M-x~ ~starhugger-complete~ or ~starhugger-complete*~ directly or bind them to your key(s) of choice. They will insert suggestion at point (turns out the overlay approach below is more useful, so maybe they will be deprecated).

The first call usually doesn't return the completed code as expected, you can call the command successively, or enable ~(starhugger-global-mode)~ and press TAB to repeat.

The performance may not be great, but they are asynchronous so Emacs won't be blocked.

- Previewing overlay: ~starhugger-trigger-suggestion~ will show the suggestion.

~M-x~ ~starhugger-show-next-suggestion~ and ~starhugger-show-prev-suggestion~ to cycle suggestions.

~M-x~ ~starhugger-accept-suggestion~ to insert current suggestion.

~starhugger-dismiss-suggestion~ (bound to =C-g= by default when showing) to cancel.

** Notes


Remember to set ~starhugger-api-token~ (from [[https://huggingface.co/settings/tokens]]), otherwise you may easily get hit by the limit rate.

Demo: [[https://www.reddit.com/r/emacs/comments/13dlycc/bigcodestarcoder_integration]].

This package is currently in a very turbulent state, expect breakages if you are using it!

* TODO

- ✓ +Support setting parameters at [[https://huggingface.co/docs/api-inference/detailed_parameters#text-generation-task]]+

- ✓ +VSCode-like previewing overlays: take after [[https://github.com/zerolfx/copilot.el]]+

- ✓ +Switching suggestion+

- ? Accept suggestion partially by words or lines

- ? TAB to complete more until "<|endoftext|>"

- ? Let ~starhugger-trigger-suggestion~ fetch about 3 suggestions to quickly cycle

- ? Fill-in-the-middle <FILL_HERE> support

- ✓ +Temporarily save the immediately previous suggestion list+

- ? More robust and reliable method to show a different suggestion

- ? Batch-previewing multiple suggestions, maybe with syntax highlighting

- ? Support for auto-completing when typing: investigate Emacs's built-in ~completion-at-point-functions~'s asynchronous capabilities, or another framework?
