An unfancy Emacs extension for [[https://huggingface.co/bigcode/starcoder]] integration.

* Installation

Add one of those to your configuration. This package also requires [[https://github.com/emacs-compat/compat][compat]] and [[https://github.com/magnars/dash.el][dash]] as dependencies.

#+begin_src elisp

;; package-vc.el (built-in from Emacs 29 and above)
(unless (package-installed-p 'starhugger)
  (package-vc-install '(starhugger :url "https://gitlab.com/daanturo/starhugger.el")))

;; straight.el
(straight-use-package '(starhugger :url "https://gitlab.com/daanturo/starhugger.el"))

;; Doom
(package! starhugger (:url "https://gitlab.com/daanturo/starhugger.el"))

;; elpaca.el
(elpaca (starhugger :url "https://gitlab.com/daanturo/starhugger.el"))

#+end_src

Or any package manager of your choice.

* Usage

Call ~M-x~ ~starhugger-complete~ or ~starhugger-complete*~ directly or bind them to your key(s) of choice.

The performance may not be great, but they are asynchronous so Emacs won't be blocked.

The first call usually doesn't return the completed code as expected, you can call the command successively, or enable ~(starhugger-global-mode)~ and press TAB to repeat.

Remember to set ~starhugger-api-token~ (from [[https://huggingface.co/settings/tokens]]), otherwise you may easily get hit by the limit rate.

Demo: [[https://www.reddit.com/r/emacs/comments/13dlycc/bigcodestarcoder_integration]].

* Unimplemented

- Support for auto-completing when typing: investigate Emacs's built-in ~completion-at-point-functions~'s asynchronous capabilities, another framework?

- VSCode-like previewing overlays: take after [[https://github.com/zerolfx/copilot.el]]
